#!/usr/bin/env python3
"""Regenerate the checked-in freestanding runtime; never run by kru itself.

Requires GNU-compatible cc, ld, objcopy and nm only during offline regeneration.
All runtime code/data lives in .text; linking at zero resolves its internal PC
relative references before extraction. The compiler copies the resulting bytes
and uses the exported symbol offsets, so runtime compilation needs no toolchain.
"""
import os
from pathlib import Path
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parent.parent
SYMBOLS = [
    'print_i32', 'print_str', 'str_len', 'str_eq', 'str_concat', 'str_index', 'file_open',
    'file_open_write', 'file_close', 'file_write', 'file_read',
    'mem_alloc', 'mem_free', 'mem_realloc', 'args_count', 'args_get',
]

def run(*args):
    return subprocess.check_output(args, text=True)


def main():
    with tempfile.TemporaryDirectory(prefix='kru-runtime-') as temporary:
        work = Path(temporary)
        obj, elf, blob = (work / name for name in ('runtime.o', 'runtime.elf', 'runtime.bin'))
        run(os.environ.get('CC', 'cc'), '-c', str(ROOT / 'tools/native_runtime.S'), '-o', str(obj))
        run(os.environ.get('LD', 'ld'), '-nostdlib', '--no-undefined', '-Ttext=0', '-e', 'rt_print_i32', str(obj), '-o', str(elf))
        # A relocation left in the linked ELF would make byte extraction unsafe.
        if run('nm', '-u', str(elf)).strip():
            raise RuntimeError('runtime contains unresolved symbols')
        run('objcopy', '-O', 'binary', '--only-section=.text', str(elf), str(blob))
        symbols = {}
        for line in run('nm', '-n', str(elf)).splitlines():
            parts = line.split()
            if len(parts) == 3:
                symbols[parts[2]] = int(parts[0], 16)
        data = blob.read_bytes()
        offsets = [symbols['rt_' + symbol] for symbol in SYMBOLS]
        if any(offset >= len(data) for offset in offsets):
            raise RuntimeError('exported runtime symbol outside blob')
        lines = [
            '/* Generated by tools/generate_native_runtime.py; do not edit. */',
            '#ifndef KRU_NATIVE_RUNTIME_BLOB_H', '#define KRU_NATIVE_RUNTIME_BLOB_H',
            '#include <stdint.h>', '', 'enum native_runtime_symbol {',
        ]
        lines += ['    RT_' + symbol.upper() + ',' for symbol in SYMBOLS]
        lines += ['    RT_COUNT', '};', '', 'static const uint32_t native_runtime_offsets[RT_COUNT] = {']
        lines += ['    ' + str(offset) + ', /* rt_' + symbol + ' */' for symbol, offset in zip(SYMBOLS, offsets)]
        lines += ['};', '', 'static const unsigned char native_runtime_blob[] = {']
        for index in range(0, len(data), 12):
            lines.append('    ' + ', '.join(f'0x{byte:02x}' for byte in data[index:index + 12]) + ',')
        lines += ['};', '', '#endif', '']
        (ROOT / 'include/native_runtime_blob.h').write_text('\n'.join(lines))
        print(f'Generated {len(data)} runtime bytes and {len(offsets)} entry offsets.')

if __name__ == '__main__':
    main()
